name: firstworkflow

on:
  push:
    branches:
      - main
      
jobs: 
  example-main:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "Welcome to our first githubaction"

      - name: checkout repository
        uses: actions/checkout@v6.0.0

      - name: List repository files
        run: ls -la


    
