name: firstworkflow

on:
  push:
    branches:
      - main
      
jobs: 
  example-main:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "Welcome to our first githubaction"


    
